# Generated by Django 4.2.4 on 2023-08-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('coleccion', models.CharField(max_length=30)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('clave', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=10)),
                ('cliente_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'consulta',
            },
        ),
    ]
